// Llista de països de la Unió Europea per al selector de dieta
export const euCountries = [
  { code: "AT", name: "Àustria" },
  { code: "BE", name: "Bèlgica" },
  { code: "BG", name: "Bulgària" },
  { code: "HR", name: "Croàcia" },
  { code: "DK", name: "Dinamarca" },
  { code: "SK", name: "Eslovàquia" },
  { code: "SI", name: "Eslovènia" },
  { code: "ES", name: "Espanya" },
  { code: "EE", name: "Estònia" },
  { code: "FI", name: "Finlàndia" },
  { code: "FR", name: "França" },
  { code: "DE", name: "Alemanya" },
  { code: "GR", name: "Grècia" },
  { code: "HU", name: "Hongria" },
  { code: "IE", name: "Irlanda" },
  { code: "IT", name: "Itàlia" },
  { code: "LV", name: "Letònia" },
  { code: "LT", name: "Lituània" },
  { code: "LU", name: "Luxemburg" },
  { code: "MT", name: "Malta" },
  { code: "NL", name: "Països Baixos" },
  { code: "PL", name: "Polònia" },
  { code: "PT", name: "Portugal" },
  { code: "CZ", name: "República Txeca" },
  { code: "RO", name: "Romania" },
  { code: "SE", name: "Suècia" },
];